### ISSUE TITLE
supbaseを利用した、サインイン・サインアップ処理

### ISSUE THREAD

**Issue by naoyuki2** [t3uyo3hi/multi-calendar-app#17]
## ゴール

サインイン・サインアップ処理が問題なく行える

## 詳細情報

[【Supabase × React】認証機能の実装方法](https://zenn.dev/sc30gsw/articles/56e07707a4f55b)
正直この記事の通りにすればできそう

## 備考

- #9 
このタスクがUIの実装なので、今回はとりあえずサインインとかができればOKです

**Comment by t3uyo3hi** [comment]
Issueありがとうございます！
UIの実装後、はじめて作業に取り掛かれる感じででしょうか？

**Comment by naoyuki2** [comment]
@t3uyo3hi 

いや！始めちゃっていいですよ！
とりあえずどこかしらに仮のフォームを作って機能を完成させちゃいましょう
で、後から合体

**Comment by t3uyo3hi** [comment]
分かりました！やってみます！
