### ISSUE TITLE
フロントエンドデザインの最終調整

### ISSUE THREAD

**Issue by t3uyo3hi** [t3uyo3hi/multi-calendar-app#18]
## ゴール

カレンダーベース/サイドパネルのデザインをFigmaを元に修正する。

## 概要

- カレンダーベースの日付けを中心部に小さく収める。
- サイドパネルの幅を広くする。
- サイドパネルの日程のサイズのバランスを整える。
- 予定の部分は文字色を #FFF にする。
- 予定の部分の背景色は #7FAFCF 固定でお願いします。

- CSSで描かれているデザインをBootstrapのデザインに変更する。
（フォントサイズなど調整に限界があるものはそのままで構いません！）
- TodoとEventの切り替えタブについてはデザインの変更があったため、今のままで大丈夫です。

## スコープ外

- モーダル

**Comment by Emi-O89** [comment]
下記を調整してfrontend-designブランチをプッシュしました

＜全体＞
・カレンダー全体のサイズと位置調整
・両端のpaddingを削除
・カレンダーパネル側の背面（親要素）に効いていなかったborder-radiusを適用

＜カレンダーパネル＞
・カレンダーを中心部に小さく収める
　→カレンダーパネルに対し70％のwidthに設定

＜サイドパネル>
・パネルの幅を拡大
・日、曜日、アカウントアイコン、イベントボタンを調整


【未調整】
・Googlefontの適用
・CSS→Bootstrapデザインに変更

**Comment by Emi-O89** [comment]
下記を調整してfrontend-designブランチをプッシュしました

■Google font "Open Sans" の適用

■CSSを可能な限りBootstrapデザインに変更
　→頻回に使用しているクラスは、タグ内にBootstrapを記述すると見にくく感じたので
　　CSSのままで残しています

**Comment by t3uyo3hi** [comment]
元のデザインにかなり近づけていただき、ありがとうございます！

## 気になった点
- **右上の角だけborder-radiusが適用されていない。**
![スクリーンショット 2024-06-27 163829](https://github.com/t3uyo3hi/multi-calendar-app/assets/153056652/35875b24-2e14-4c12-a442-b7e0884870d1)



- **Open Sansの適用がUIに反映されていない。**

- **ディスプレイによっては、縦に間延びしてしまい、サイドパネル部分が窮屈に感じてしまう。**
デフォルトのアスペクト比を設定し、ディスプレイサイズが小さくなっても、その比率を維持できるようにしていただきたいです。（急なお願いになってしまい申し訳ありません。難しい場合はここは新たにIssueを出し後回しにするか、他の人にお願いしてしまっても良いと思います！）
![スクリーンショット 2024-06-27 163847](https://github.com/t3uyo3hi/multi-calendar-app/assets/153056652/63c34bec-fd74-46bd-83e9-961d76317f11)
