### ISSUE TITLE
サイドバーの作成

### ISSUE THREAD

**Issue by naoyuki2** [t3uyo3hi/multi-calendar-app#7]
## ゴール

[Figma](https://www.figma.com/design/Id4lR463G2wSGGXwpdQbfm/%E5%A4%9A%E6%A9%9F%E8%83%BD%E3%82%AB%E3%83%AC%E3%83%B3%E3%83%80%E3%83%BC%E5%88%B6%E4%BD%9C?node-id=0-1&t=mxS59vDic7FO1sWO-0)のデザイン通りのサイドバーが表示されている

<img src="https://github.com/t3uyo3hi/multi-calendar-app/assets/135786069/efc05be0-97d3-4c93-a28c-9be9e91713db" width="500" />

## スコープ外

- 天気のアイコン(おそらく外部のAPIで取得できたはず)
- カレンダー
- バックエンド

## 備考

見た目だけ作っていただければOKです。バックエンドとか、クリックしたらモーダルを出すか、などはとりあえず考えないでおきましょう。

タスクなども仮の値をハードコーディングをしておきましょう

**Comment by t3uyo3hi** [comment]
お疲れさまでした！！
