### ISSUE TITLE
ログイン・サインアップモーダルの作成

### ISSUE THREAD

**Issue by naoyuki2** [t3uyo3hi/multi-calendar-app#9]
## ゴール

[Figma](https://www.figma.com/design/Id4lR463G2wSGGXwpdQbfm/%E5%A4%9A%E6%A9%9F%E8%83%BD%E3%82%AB%E3%83%AC%E3%83%B3%E3%83%80%E3%83%BC%E5%88%B6%E4%BD%9C?node-id=0-1&t=mxS59vDic7FO1sWO-0)のデザイン通りのログイン・サインアップモーダルが表示されている

下画像のユーザーアイコンクリックでログインモーダルを表示する

<img src="https://github.com/t3uyo3hi/multi-calendar-app/assets/135786069/a0d4eb4e-962f-4736-a37b-9775e5e0c394" width="400" />

<img src="https://github.com/t3uyo3hi/multi-calendar-app/assets/135786069/797bd885-f771-4854-a7e8-d2579d688f60" width="400" />

<img src="https://github.com/t3uyo3hi/multi-calendar-app/assets/135786069/965e842f-88f9-4edb-ae9a-16a787b9b7fe" width="400" />

## 条件

- Bootstrapを使用してモーダルを作成する
- ログイン・サインアップ両方作ってほしい

## スコープ外

- バックエンド

**Comment by t3uyo3hi** [comment]
ISSUE完了しました。こうきちさんお疲れ様です！
